piraña/Models/Contacto.cs
namespace piraña.Models
{
    public class Contacto
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Mensaje { get; set; }
    }
}

piraña/Models/ErrorViewModel.cs
using System;

namespace piraña.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

piraña/Models/Usuario.cs
namespace piraña.Models
{
    public class Usuario
    {
        public int id { get; set; }
        public string Usuarios { get; set; }
        public string Contraseña { get; set; }
    }
}

piraña/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using piraña.Models;

namespace piraña.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

piraña/Controllers/infantilesController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using piraña.Data;
using piraña.Models;

namespace piraña.Controllers
{
        public class infantilesController : Controller
        {
            private infantilesContext _context;

            public infantilesController(infantilesContext context)
            {
                _context = context;
            }
            public IActionResult Contacto(){
            return View();
        }
             [HttpPost]
       public IActionResult Nuevo(Usuario u) {
           if (ModelState.IsValid) {
               //Guardar objeto pueblo en la BD
               _context.Add(u);
               _context.SaveChanges();

               return RedirectToAction("Lista");
           }
            return View(u);
        }
        public IActionResult Lista() {
            var infantiles = _context.infantiles.OrderBy(x => x.Usuarios).ToList();
            return View(infantiles);
        }
    }
}

piraña/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

piraña/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - piraña</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">piraña</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="infantiles" asp-action="presentacion">Presentacion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="infantiles" asp-action="venta">Venta de Productos y servicios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="infantiles" asp-action="compra">Compra de Productos y servicios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="infantiles" asp-action="cuenta">Cuenta de Usuario</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - piraña - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

piraña/Views/infantiles/Contacto.cshtml
@model Contacto
<h1> Realizar un mensaje para contactar</h1>

<form method="Post">
    <div class="form-group">
         <label asp-for="Nombre"> </label> 
         <input asp-for="Nombre" class="form-control">
    </div>
     <div class="form-group">
         <label asp-for="Mensaje"> </label> 
         <input asp-for="Mensaje" class="form-control">
    </div>

    <button class="btn btn-primary"> Enviar Mensaje </button>
</form>

piraña/Views/infantiles/Lista.cshtml
@model List<Usuario>
<h1> Lista de Clientes registrados en nuestra tienda Piraña</h1>

@if (Model.Count == 0) {
    <div class="alert alert-warning text-center"> Aun no hay usuarios registrados </div>
} else {
    <ol>
    @foreach (var p in Model) {
        <li class="d-flex">
            <div>"u.Usuarios"/></div>
            <div>u.Usuarios</div>
        </li> 
    }
    </ol>
}

piraña/Views/infantiles/Registro.cshtml
@model Usuario
<h1> Registrar nuevo Usuario </h1>

<form method="Post">
    <div class="form-group">
         <label asp-for="Usuarios"> </label> 
         <input asp-for="Usuarios" class="form-control">
    </div>
     <div class="form-group">
         <label asp-for="Contraseña"> </label> 
         <input asp-for="Contraseña" class="form-control">
    </div>

    <button class="btn btn-primary"> Registrar Usuario </button>
</form>

piraña/Views/infantiles/presentacion.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<main role="main">
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">

    <div class="carousel-item active">
            <img src="~/img/fiestas.jpg"  class="d-block w-100"  alt="..." style="width: 1150px; height:600px">
           
      <div  style="text-align: center;" class="carousel-caption">
            <h1 style="position: relative;right: 500px ;top: -215px" class="text-white"> Fiestas</h1>
            <h1 style="position: relative;right: 490px ;top: -210px" class="text-white">Infantiles </h1>
            <h1 style="position: relative;right: 500px ;top: -205px" class="text-white"> Piraña</h1>          
            <button style="position: relative;right: 450px ;top: -150px "  class="btn btn-dark btn-lg" >Conocer mas </button>
          </div>
    </div>

    <div class="carousel-item ">
       <img src="~/img/animacion.jpg" class="d-block w-100" alt="..." style="width: 1150px; height:600px">
       <div  style="text-align: center;" class="carousel-caption">
            <h1 style="position: relative;right: 500px ;top: -215px" class="text-white">Animacion</h1>
            <button style="position: relative;right: 450px ;top: -150px "  class="btn btn-dark btn-lg" >¡SOLICITAR COTIZACION! </button>
          </div>
    </div>

    <div class="carousel-item ">
       <img src="~/img/diseño.jpg" class="d-block w-100" alt="..." style="width: 1150px; height:600px">
       <div  style="text-align: center;" class="carousel-caption">
            <h1 style="position: relative;right: 500px ;top: -215px" class="text-dark"> Diseño de Fiestas </h1>
            <button style="position: relative;right: 450px ;top: -150px "  class="btn btn-dark btn-lg" >¡SOLICITAR COTIZACION! </button>
          </div>
    </div>
    <div class="carousel-item ">
       <img src="~/img/alquiler.jpg" class="d-block w-100" alt="..." style="width: 1150px; height:600px">
       <div  style="text-align: center;" class="carousel-caption">
            <h1 style="position: relative;right: 500px ;top: -230px" class="text-dark"> Alquiler de Equipos de Sonido </h1>
            <button style="position: relative;right: 450px ;top: -150px "  class="btn btn-dark btn-lg" >¡SOLICITAR COTIZACION! </button>
          </div>
    </div>
    <div class="carousel-item ">
       <img src="~/img/payasos.jpg" class="d-block w-100" alt="..." style="width: 1150px; height:600px">
       <div  style="text-align: center;" class="carousel-caption">
            <h1 style="position: relative;right: 490px ;top: -210px" class="text-dark">Payasos</h1>
            <button style="position: relative;right: 450px ;top: -150px "  class="btn btn-dark btn-lg" >¡SOLICITAR COTIZACION! </button>
          </div>
    </div>

     <div class="carousel-item ">
       <img src="~/img/disfraces.jpg" class="d-block w-100" alt="..." style="width: 1150px; height:600px">
       <div  style="text-align: center;" class="carousel-caption">
            <h1 style="position: relative;right: 500px ;top: -215px" class="text-dark">Disfraces</h1>
            <button style="position: relative;right: 450px ;top: -150px "  class="btn btn-dark btn-lg" >¡SOLICITAR COTIZACION! </button>
          </div>
    </div>

  <a class="carousel-control-prev" href="#carouselExampleControls"  role="button"  data-slide="prev">
    <span class="carousel-control-prev-icon " aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
    
  </a>
  
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>